version: '3.9'

services:

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB: ${POSTGRES_DATABASE}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  service:
    image: registry.https://github.com/zepif/Test-service
    environment:
      KV_VIPER_FILE: /app/config.yaml
      DATABASE_URL: postgres://tokend:changeme@db/tokend?sslmode=disable
    depends_on:
      - db
    volumes:
      - ./config.yaml:/app/config.yaml

  nginx:
    image: nginx:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:80"   # http
      - "8443:443"  # https
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - service

volumes:
  db-data:
