on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'main'

env:
  CI_JOB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Log in to registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u USERNAME --password-stdin

      - name: Run echo
        run: |
          werf version
          docker version
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA

      - name: Run Build
        run: |
          . $(werf ci-env github --as-file)
          werf export service --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
